services:
  app_financesdb:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile.financesdb
    environment:
      CONNECTION_URI: $APP_FINANCESDB_CONNECTION_URI
      HASURA_SERVICE_TOKEN_SECRET: $APP_FINANCESDB_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_ENDPOINT: $APP_FINANCESDB_OTEL_EXPORTER_OTLP_ENDPOINT
      OTEL_SERVICE_NAME: $APP_FINANCESDB_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev:host-gateway
    ports:
      - 8043:8080
